# Generated by Django 4.0 on 2024-11-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='stripe_price_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='stripe_product_id',
            field=models.CharField(default=1, max_length=100, verbose_name='商品ID'),
            preserve_default=False,
        ),
    ]
