# Generated by Django 4.0 on 2024-11-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allergy',
        ),
    ]
