# Generated by Django 4.0 on 2024-11-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_category_image'),
        ('foods', '0003_food_stripe_price_id_food_stripe_product_id'),
    ]

    operations = [
    ]
