# Generated by Django 4.0 on 2024-10-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=10, unique=True)),
                ('product_name', models.CharField(choices=[('A', '商品A'), ('B', '商品B')], max_length=1)),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_method', models.CharField(choices=[('standard', '通常配送'), ('express', '速達配送'), ('pickup', '店舗受取')], default='standard', max_length=10)),
            ],
        ),
    ]
