<<<<<<< HEAD
# Generated by Django 4.0 on 2025-01-24 01:45
=======
# Generated by Django 4.0 on 2025-01-24 01:25
>>>>>>> 04b5f0f9c1834bc2f755ed693d10ba240b174c70

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
