# Generated by Django 4.0 on 2024-10-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_order_shipped_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('standard', '通常配送'), ('express', '速達配送')], default='standard', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(choices=[('A', '商品A'), ('B', '商品B'), ('C', '商品C')], max_length=1),
        ),
    ]
