# Generated by Django 4.0 on 2025-01-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgroupLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
