# Generated by Django 4.0 on 2024-10-31 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='FoodInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('stock', models.IntegerField(verbose_name='数量')),
                ('shelf_life', models.DateField(verbose_name='賞味期限')),
                ('allergy', models.CharField(max_length=150, verbose_name='アレルギー')),
                ('image', models.ImageField(upload_to='images', verbose_name='写真')),
                ('inputed_at', models.DateField(auto_now_add=True, verbose_name='入力日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dgroupapp.category', verbose_name='カテゴリ')),
            ],
        ),
    ]
