# Generated by Django 4.0 on 2024-10-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgroupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='アレルギー食材名')),
            ],
        ),
    ]
