# Generated by Django 4.0 on 2024-11-06 03:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgroupapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinput',
            name='shelf_life',
            field=models.DateField(default=datetime.datetime(2024, 11, 6, 3, 14, 0, 241891, tzinfo=utc), verbose_name='賞味期限'),
        ),
    ]
