# Generated by Django 4.0 on 2024-11-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgroupapp', '0002_alter_foodinput_shelf_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinput',
            name='shelf_life',
            field=models.DateField(verbose_name='賞味期限'),
        ),
    ]
