# Generated by Django 4.0 on 2024-11-15 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgroupapp', '0003_alter_foodinput_shelf_life'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.RemoveField(
            model_name='foodinput',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FoodInput',
        ),
    ]
