# Generated by Django 4.0 on 2024-12-02 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgroupLogin', '0001_initial'),
        ('purchaseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpost',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='追加日時'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment_intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent', models.CharField(max_length=9999)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgroupLogin.customuser', verbose_name='ユーザー')),
            ],
        ),
    ]
