# Generated by Django 4.0 on 2024-12-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseapp', '0002_cartpost_added_at_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpost',
            name='shipped',
        ),
        migrations.RemoveField(
            model_name='orderpost',
            name='shipped_date',
        ),
        migrations.AlterField(
            model_name='buyjudge',
            name='stock',
            field=models.IntegerField(verbose_name='追加数'),
        ),
    ]
