# Generated by Django 4.0 on 2024-11-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseapp', '0002_product_cartpost_allergy_cartpost_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_product_id', models.CharField(max_length=100, verbose_name='商品ID')),
                ('stock', models.IntegerField(verbose_name='購入数')),
            ],
        ),
    ]
