# Generated by Django 4.0 on 2025-01-14 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseapp', '0004_orderpost_shipped_orderpost_shipped_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpost',
            name='ordertime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='注文日時'),
            preserve_default=False,
        ),
    ]
