# Generated by Django 4.0 on 2025-01-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseapp', '0005_orderpost_ordertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpost',
            name='postal_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号'),
        ),
    ]
